/**
 * generated by Xtext 2.16.0
 */
package br.ufes.inf.nemo.ml2.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class ML2QuickfixProvider extends DefaultQuickfixProvider {
}
