/*
 * generated by Xtext 2.21.0
 */
package br.ufes.inf.nemo.ml2;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ML2RuntimeModule extends AbstractML2RuntimeModule {
}
