<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ML2" nsURI="http://www.ufes.br/inf/nemo/ml2" nsPrefix="metamodel">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ModelElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="includes" upperBound="-1"
        eType="#//Model"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Import" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityDeclaration" abstract="true" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instantiates" upperBound="-1"
        eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignments" upperBound="-1"
        eType="#//FeatureAssignment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class" abstract="true" eSuperTypes="#//EntityDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superClasses" upperBound="-1"
        eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subordinators" upperBound="-1"
        eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="powertypeOf" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="categorizedClass" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="categorizationType" eType="#//CategorizationType"
        defaultValueLiteral="categorizes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" upperBound="-1"
        eType="#//Feature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CategorizationType">
    <eLiterals name="CATEGORIZES" value="1" literal="categorizes"/>
    <eLiterals name="DISJOINT_CATEGORIZER" value="2" literal="disjointCategorizes"/>
    <eLiterals name="OMPLETE_CATEGORIZER" value="3" literal="completeCategorizes"/>
    <eLiterals name="PARTITIONER" value="4" literal="partitions"/>
    <eLiterals name="NONE" literal="none"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrderlessClass" eSuperTypes="#//Class"/>
  <eClassifiers xsi:type="ecore:EClass" name="HOClass" eSuperTypes="#//Class">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="order" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FOClass" eSuperTypes="#//Class"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataType" eSuperTypes="#//FOClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="Individual" eSuperTypes="#//EntityDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="GeneralizationSet" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDisjoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isComplete" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="general" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="categorizer" eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specifics" upperBound="-1"
        eType="#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="regularityType" eType="#//RegularityFeatureType"
        defaultValueLiteral="none"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="regulatedFeature" eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subsetOf" upperBound="-1"
        eType="#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RegularityFeatureType" instanceTypeName="RegularityFeatureType">
    <eLiterals name="NONE" literal="none"/>
    <eLiterals name="DETERMINES_MAX_VALUE" value="1" literal="determinesMaxValue"/>
    <eLiterals name="DETERMINES_MIN_VALUE" value="2" literal="determinesMinValue"/>
    <eLiterals name="DETERMINES_VALUE" value="3" literal="determinesValue"/>
    <eLiterals name="DETERMINES_ALLOWED_VALUES" value="4" literal="determinesAllowedValues"/>
    <eLiterals name="DETERMINES_TYPE" value="5" literal="determinesType"/>
    <eLiterals name="DETERMINES_ALLOWED_TYPES" value="6" literal="determinesAllowedTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="_type" eType="#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primitiveType" eType="#//PrimitiveType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="literalAssignments" upperBound="-1"
        eType="#//Literal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="_type" eType="#//FOClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oppositeTo" eType="#//Reference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureAssignment" eSuperTypes="#//ModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeAssignment" eSuperTypes="#//FeatureAssignment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" eType="#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="individualAssignments"
        upperBound="-1" eType="#//Individual"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unnamedIndividualAssignments"
        upperBound="-1" eType="#//Individual" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceAssignment" eSuperTypes="#//FeatureAssignment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignments" upperBound="-1"
        eType="#//EntityDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="#//Reference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PrimitiveType" instanceTypeName="PrimitiveType">
    <eLiterals name="NONE" literal="none"/>
    <eLiterals name="STRING" value="1" literal="String"/>
    <eLiterals name="NUMBER" value="2" literal="Number"/>
    <eLiterals name="BOOLEAN" value="3" literal="Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literal" abstract="true" eSuperTypes="#//ModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="String" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Number" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Boolean" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
