/**
 * generated by Xtext 2.21.0
 */
package br.ufes.inf.nemo.ml2.model;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufes.inf.nemo.ml2.model.AttributeAssignment#getAttribute <em>Attribute</em>}</li>
 *   <li>{@link br.ufes.inf.nemo.ml2.model.AttributeAssignment#getStringValues <em>String Values</em>}</li>
 *   <li>{@link br.ufes.inf.nemo.ml2.model.AttributeAssignment#getNumberValues <em>Number Values</em>}</li>
 *   <li>{@link br.ufes.inf.nemo.ml2.model.AttributeAssignment#getBooleanValues <em>Boolean Values</em>}</li>
 *   <li>{@link br.ufes.inf.nemo.ml2.model.AttributeAssignment#getDatatypeValues <em>Datatype Values</em>}</li>
 *   <li>{@link br.ufes.inf.nemo.ml2.model.AttributeAssignment#getUnnamedValues <em>Unnamed Values</em>}</li>
 * </ul>
 *
 * @see br.ufes.inf.nemo.ml2.model.ModelPackage#getAttributeAssignment()
 * @model
 * @generated
 */
public interface AttributeAssignment extends FeatureAssignment
{
  /**
   * Returns the value of the '<em><b>Attribute</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute</em>' reference.
   * @see #setAttribute(Attribute)
   * @see br.ufes.inf.nemo.ml2.model.ModelPackage#getAttributeAssignment_Attribute()
   * @model
   * @generated
   */
  Attribute getAttribute();

  /**
   * Sets the value of the '{@link br.ufes.inf.nemo.ml2.model.AttributeAssignment#getAttribute <em>Attribute</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute</em>' reference.
   * @see #getAttribute()
   * @generated
   */
  void setAttribute(Attribute value);

  /**
   * Returns the value of the '<em><b>String Values</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>String Values</em>' attribute list.
   * @see br.ufes.inf.nemo.ml2.model.ModelPackage#getAttributeAssignment_StringValues()
   * @model unique="false"
   * @generated
   */
  EList<String> getStringValues();

  /**
   * Returns the value of the '<em><b>Number Values</b></em>' attribute list.
   * The list contents are of type {@link java.lang.Double}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number Values</em>' attribute list.
   * @see br.ufes.inf.nemo.ml2.model.ModelPackage#getAttributeAssignment_NumberValues()
   * @model unique="false"
   * @generated
   */
  EList<Double> getNumberValues();

  /**
   * Returns the value of the '<em><b>Boolean Values</b></em>' attribute list.
   * The list contents are of type {@link java.lang.Boolean}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Boolean Values</em>' attribute list.
   * @see br.ufes.inf.nemo.ml2.model.ModelPackage#getAttributeAssignment_BooleanValues()
   * @model unique="false"
   * @generated
   */
  EList<Boolean> getBooleanValues();

  /**
   * Returns the value of the '<em><b>Datatype Values</b></em>' reference list.
   * The list contents are of type {@link br.ufes.inf.nemo.ml2.model.Individual}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Datatype Values</em>' reference list.
   * @see br.ufes.inf.nemo.ml2.model.ModelPackage#getAttributeAssignment_DatatypeValues()
   * @model
   * @generated
   */
  EList<Individual> getDatatypeValues();

  /**
   * Returns the value of the '<em><b>Unnamed Values</b></em>' containment reference list.
   * The list contents are of type {@link br.ufes.inf.nemo.ml2.model.Individual}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unnamed Values</em>' containment reference list.
   * @see br.ufes.inf.nemo.ml2.model.ModelPackage#getAttributeAssignment_UnnamedValues()
   * @model containment="true"
   * @generated
   */
  EList<Individual> getUnnamedValues();

} // AttributeAssignment
