/**
 * generated by Xtext 2.21.0
 */
package br.ufes.inf.nemo.ml2.model;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Binary Set Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufes.inf.nemo.ml2.model.BinarySetOperation#getOperator <em>Operator</em>}</li>
 *   <li>{@link br.ufes.inf.nemo.ml2.model.BinarySetOperation#getArgument <em>Argument</em>}</li>
 * </ul>
 *
 * @see br.ufes.inf.nemo.ml2.model.ModelPackage#getBinarySetOperation()
 * @model
 * @generated
 */
public interface BinarySetOperation extends ArrowOperation
{
  /**
   * Returns the value of the '<em><b>Operator</b></em>' attribute.
   * The literals are from the enumeration {@link br.ufes.inf.nemo.ml2.model.BinarySetOperator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' attribute.
   * @see br.ufes.inf.nemo.ml2.model.BinarySetOperator
   * @see #setOperator(BinarySetOperator)
   * @see br.ufes.inf.nemo.ml2.model.ModelPackage#getBinarySetOperation_Operator()
   * @model
   * @generated
   */
  BinarySetOperator getOperator();

  /**
   * Sets the value of the '{@link br.ufes.inf.nemo.ml2.model.BinarySetOperation#getOperator <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' attribute.
   * @see br.ufes.inf.nemo.ml2.model.BinarySetOperator
   * @see #getOperator()
   * @generated
   */
  void setOperator(BinarySetOperator value);

  /**
   * Returns the value of the '<em><b>Argument</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Argument</em>' containment reference.
   * @see #setArgument(OclExpression)
   * @see br.ufes.inf.nemo.ml2.model.ModelPackage#getBinarySetOperation_Argument()
   * @model containment="true"
   * @generated
   */
  OclExpression getArgument();

  /**
   * Sets the value of the '{@link br.ufes.inf.nemo.ml2.model.BinarySetOperation#getArgument <em>Argument</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Argument</em>' containment reference.
   * @see #getArgument()
   * @generated
   */
  void setArgument(OclExpression value);

} // BinarySetOperation
