/**
 * generated by Xtext 2.21.0
 */
package br.ufes.inf.nemo.ml2.model;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Call Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufes.inf.nemo.ml2.model.CallExpression#getLeft <em>Left</em>}</li>
 *   <li>{@link br.ufes.inf.nemo.ml2.model.CallExpression#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see br.ufes.inf.nemo.ml2.model.ModelPackage#getCallExpression()
 * @model
 * @generated
 */
public interface CallExpression extends TermExpression
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(VariableExpression)
   * @see br.ufes.inf.nemo.ml2.model.ModelPackage#getCallExpression_Left()
   * @model containment="true"
   * @generated
   */
  VariableExpression getLeft();

  /**
   * Sets the value of the '{@link br.ufes.inf.nemo.ml2.model.CallExpression#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(VariableExpression value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference list.
   * The list contents are of type {@link br.ufes.inf.nemo.ml2.model.CallOperation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference list.
   * @see br.ufes.inf.nemo.ml2.model.ModelPackage#getCallExpression_Right()
   * @model containment="true"
   * @generated
   */
  EList<CallOperation> getRight();

} // CallExpression
