/**
 * generated by Xtext 2.21.0
 */
package br.ufes.inf.nemo.ml2.model;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Call Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see br.ufes.inf.nemo.ml2.model.ModelPackage#getCallOperation()
 * @model
 * @generated
 */
public interface CallOperation extends EObject
{
} // CallOperation
