/**
 * generated by Xtext 2.21.0
 */
package br.ufes.inf.nemo.ml2.model;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see br.ufes.inf.nemo.ml2.model.ModelPackage#getDataType()
 * @model
 * @generated
 */
public interface DataType extends FirstOrderClass
{
} // DataType
