/**
 * generated by Xtext 2.21.0
 */
package br.ufes.inf.nemo.ml2.model;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Derivation Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufes.inf.nemo.ml2.model.DerivationConstraint#getFeatureContext <em>Feature Context</em>}</li>
 *   <li>{@link br.ufes.inf.nemo.ml2.model.DerivationConstraint#getTypename <em>Typename</em>}</li>
 * </ul>
 *
 * @see br.ufes.inf.nemo.ml2.model.ModelPackage#getDerivationConstraint()
 * @model
 * @generated
 */
public interface DerivationConstraint extends Constraint
{
  /**
   * Returns the value of the '<em><b>Feature Context</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Feature Context</em>' reference.
   * @see #setFeatureContext(Feature)
   * @see br.ufes.inf.nemo.ml2.model.ModelPackage#getDerivationConstraint_FeatureContext()
   * @model
   * @generated
   */
  Feature getFeatureContext();

  /**
   * Sets the value of the '{@link br.ufes.inf.nemo.ml2.model.DerivationConstraint#getFeatureContext <em>Feature Context</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Feature Context</em>' reference.
   * @see #getFeatureContext()
   * @generated
   */
  void setFeatureContext(Feature value);

  /**
   * Returns the value of the '<em><b>Typename</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Typename</em>' containment reference.
   * @see #setTypename(TypeLiteralExpression)
   * @see br.ufes.inf.nemo.ml2.model.ModelPackage#getDerivationConstraint_Typename()
   * @model containment="true"
   * @generated
   */
  TypeLiteralExpression getTypename();

  /**
   * Sets the value of the '{@link br.ufes.inf.nemo.ml2.model.DerivationConstraint#getTypename <em>Typename</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Typename</em>' containment reference.
   * @see #getTypename()
   * @generated
   */
  void setTypename(TypeLiteralExpression value);

} // DerivationConstraint
