/**
 * generated by Xtext 2.21.0
 */
package br.ufes.inf.nemo.ml2.model;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>First Order Class</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see br.ufes.inf.nemo.ml2.model.ModelPackage#getFirstOrderClass()
 * @model
 * @generated
 */
public interface FirstOrderClass extends br.ufes.inf.nemo.ml2.model.Class, OrderedClass
{
} // FirstOrderClass
