/**
 * generated by Xtext 2.21.0
 */
package br.ufes.inf.nemo.ml2.model;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reference Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufes.inf.nemo.ml2.model.ReferenceAssignment#getReference <em>Reference</em>}</li>
 *   <li>{@link br.ufes.inf.nemo.ml2.model.ReferenceAssignment#getValues <em>Values</em>}</li>
 * </ul>
 *
 * @see br.ufes.inf.nemo.ml2.model.ModelPackage#getReferenceAssignment()
 * @model
 * @generated
 */
public interface ReferenceAssignment extends FeatureAssignment
{
  /**
   * Returns the value of the '<em><b>Reference</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reference</em>' reference.
   * @see #setReference(Reference)
   * @see br.ufes.inf.nemo.ml2.model.ModelPackage#getReferenceAssignment_Reference()
   * @model
   * @generated
   */
  Reference getReference();

  /**
   * Sets the value of the '{@link br.ufes.inf.nemo.ml2.model.ReferenceAssignment#getReference <em>Reference</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reference</em>' reference.
   * @see #getReference()
   * @generated
   */
  void setReference(Reference value);

  /**
   * Returns the value of the '<em><b>Values</b></em>' reference list.
   * The list contents are of type {@link br.ufes.inf.nemo.ml2.model.EntityDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Values</em>' reference list.
   * @see br.ufes.inf.nemo.ml2.model.ModelPackage#getReferenceAssignment_Values()
   * @model
   * @generated
   */
  EList<EntityDeclaration> getValues();

} // ReferenceAssignment
