/**
 * generated by Xtext 2.21.0
 */
package br.ufes.inf.nemo.ml2.model;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Set Literal Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufes.inf.nemo.ml2.model.SetLiteralExpression#getParts <em>Parts</em>}</li>
 * </ul>
 *
 * @see br.ufes.inf.nemo.ml2.model.ModelPackage#getSetLiteralExpression()
 * @model
 * @generated
 */
public interface SetLiteralExpression extends LiteralExpression
{
  /**
   * Returns the value of the '<em><b>Parts</b></em>' containment reference list.
   * The list contents are of type {@link br.ufes.inf.nemo.ml2.model.PrimitiveLiteralExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parts</em>' containment reference list.
   * @see br.ufes.inf.nemo.ml2.model.ModelPackage#getSetLiteralExpression_Parts()
   * @model containment="true"
   * @generated
   */
  EList<PrimitiveLiteralExpression> getParts();

} // SetLiteralExpression
