/**
 * generated by Xtext 2.21.0
 */
package br.ufes.inf.nemo.ml2.model;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Literal Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see br.ufes.inf.nemo.ml2.model.ModelPackage#getTypeLiteralExpression()
 * @model
 * @generated
 */
public interface TypeLiteralExpression extends LiteralExpression
{
} // TypeLiteralExpression
