/*
 * generated by Xtext 2.21.0
 */
package br.ufes.inf.nemo.ml2.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractML2Validator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(br.ufes.inf.nemo.ml2.model.ModelPackage.eINSTANCE);
		return result;
	}
}
