/*
 * generated by Xtext 2.21.0
 */
package br.ufes.inf.nemo.ml2.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractML2ScopeProvider extends DelegatingScopeProvider {
}
