/**
 * generated by Xtext 2.10.0
 */
package br.ufes.inf.nemo.ml2.validation;

import br.ufes.inf.nemo.ml2.validation.AbstractML2Validator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ML2Validator extends AbstractML2Validator {
}
